### ISSUE TITLE
How to find the paper ?

### ISSUE THREAD

**Issue by zhgqcn** [jsobbe/meta_nilm#12]
![image](https://user-images.githubusercontent.com/44897668/210236930-fb8f6c6e-9c1e-4ad8-a809-50b9dbb58cfa.png)

**Comment by jsobbe** [comment]
Hi, sorry for the late reply!
You cannot find it because it was never published as a paper. The master thesis was simply submitted to the university and the repository was only meant as a code reference. 
In case you still want to read it though: I created a new branch _thesis_ where I uploaded the paper. (See [commit c41cf26](https://github.com/jsobbe/meta_nilm/commit/c41cf26e565ed2da00350bddabdd9e8605864c6a)).
